NXP-23110: properly refresh main search URL on search selection
nuxeo/nuxeo-jsf-ui pull request #91
Opened 2020-12-09 09:02 UTC by atchertchian

2020-12-09 09:02 UTC, nuxeojenkins commented
View issue in JIRA: [NXP-23110](https://jira.nuxeo.com/browse/NXP-23110): Wrong saved search when clicking Search tab

2020-12-09 09:09 UTC, ataillefer submitted a review, later dismissed

2020-12-09 10:24 UTC, troger approved these changes, later dismissed

2020-12-09 13:07 UTC, atchertchian commented
ftests show an error on logs because of dc:creator being readonly when restoring search content view state: will need to adapt the logics here

2020-12-09 16:10 UTC, efge requested changes

2020-12-09 16:10 UTC, efge commented on code/nuxeo-platform-contentview-jsf/src/main/java/org/nuxeo/ecm/platform/contentview/json/JSONContentViewState.java
> +                doc.setPropertyValue(key, getDocumentPropertyValue(props.get(key)));
Could be just `prop.setValue(getDocumentPropertyValue(props.get(key)))` now

2020-12-09 16:20 UTC, efge approved these changes

2020-12-10 09:34 UTC, ataillefer approved these changes

2020-12-10 10:38 UTC, merged